import React,{useEffect,useRef,useState} from "react";
type Api=(path:string,init?:RequestInit)=>Promise<any>;
export function MessageHistory({runId,node,edge,captureEdges,csrf,api,onArtifact}:{runId:string,node:string,edge:string,captureEdges:string[],csrf:string,api:Api,onArtifact:(id:string,edge:string)=>void}){
 const [captureEdge,setCaptureEdge]=useState(edge);
 const [stream,setStream]=useState(""),[cursor,setCursor]=useState<string|null>(null),[data,setData]=useState<any>(null),[queryError,setQueryError]=useState(""),[actionError,setActionError]=useState(""),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false);
 const fence=useRef(0);
 useEffect(()=>{fence.current++;setResult(null);setActionError("");setBusy(false);return()=>{fence.current++;};},[runId,node,captureEdge,stream,cursor]);
 useEffect(()=>{let active=true,pending=false;setData(null);setQueryError("");if(!node)return;async function refresh(){if(pending)return;pending=true;try{const value=await api(`runs/${runId}/messages/query`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({node,...(stream?{stream}:{}),...(cursor?{cursor}:{})})});if(active){setData(value);setQueryError("");}}catch(e){if(active)setQueryError((e as Error).message);}finally{pending=false;}}void refresh();const timer=cursor?null:setInterval(refresh,3000);return()=>{active=false;if(timer)clearInterval(timer);};},[runId,node,stream,cursor,csrf,api]);
 async function correlate(id:string){const generation=++fence.current;setBusy(true);setResult(null);setActionError("");try{const value=await api(`runs/${runId}/messages/correlate`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({node,id,...(captureEdge?{edge:captureEdge}:{})})});if(generation===fence.current)setResult(value);}catch(e){if(generation===fence.current)setActionError((e as Error).message);}finally{if(generation===fence.current)setBusy(false);}}
 return <section aria-label="Application message observations"><h3>Application message observations</h3>
 <p>Opt-in endpoint events, separate from packets and aggregate counters. Payload recording disabled. Delivery accounting and loss: unavailable. Missing observations do not prove loss.</p>
 {!node?<p>Select a reporting workload node. Legacy workloads may provide no message observations.</p>:<>
 <p>Reporting node {node} · correlation scope: {captureEdge?`network edge ${captureEdge}`:"retained run captures (union; occurrences remain distinct)"}. GLM1/v1 UDP fixture identifiers only; no TCP reassembly or encrypted-payload correlation.</p>
 <label>Correlation capture edge <select value={captureEdge} onChange={e=>setCaptureEdge(e.target.value)}><option value="">Retained run captures (union)</option>{[...new Set([...captureEdges,captureEdge].filter(Boolean))].map(e=><option key={e}>{e}</option>)}</select></label>
 <label>Message stream <select value={stream} onChange={e=>{setStream(e.target.value);setCursor(null);}}><option value="">All fixture streams</option><option>alpha</option><option>beta</option></select></label>
 {queryError&&<p role="alert">History: {queryError}</p>}{actionError&&<p role="alert">Correlation: {actionError}</p>}{data?.error&&<p role="alert">Collection: {data.error}</p>}{data?.sourceCapacityReached&&<p role="alert">Reporter catalog capacity reached; further reporters may be omitted.</p>}
 {data?.sources?.map((s:any)=><p key={`${s.instance}/${s.epoch}`}>Reporter {s.epoch} · {s.stale?"stale / retained":"recently observed"} · {s.missedBeforeIngestion} events missed before ingestion · {s.reporterEvicted} evicted by reporter · {s.expiredOrPruned} expired/pruned · {s.retained} retained</p>)}
 <p>{cursor?"Frozen older message page":"Newest message observations (refreshing)"} · 24-hour / 4 MiB / 4,096-event global retention.</p>
 <button disabled={!data?.nextCursor} onClick={()=>setCursor(data.nextCursor)}>Older message observations</button>{" "}<button onClick={()=>{setCursor(null);setResult(null);setActionError("");fence.current++;setBusy(false);}}>Return to newest messages</button>
 {data&&!data.items?.length&&<p>No retained message observations. Unsupported or unobserved output is unavailable.</p>}
 <ul>{data?.items?.map((e:any)=><li key={e.id}><strong>{e.observation.kind} · {e.observation.stream} · {e.observation.phase}</strong> · event {e.observation.sequence} · {e.observation.payloadLength} payload bytes<br/>Message {e.observation.messageId} · trace {e.observation.traceId}<br/>Reporter monotonic ns {e.observation.timestampMonotonicNs}; clocks are local to the reporter epoch, not synchronized.<br/><button disabled={busy} onClick={()=>void correlate(e.id)}>Correlate event {e.id}</button></li>)}</ul>
 {result&&<section aria-label="Message capture correlation"><h4>Correlation: {result.status}</h4><p>{result.reason}</p><p>Run coverage: {result.captureCoverage} · retained-scope scan {result.searchComplete?"complete":"incomplete"}. No delivery or latency inferred.</p>{result.errors?.map((e:string,i:number)=><p role="alert" key={i}>{e}</p>)}<ul>{result.matches?.map((m:any)=><li key={`${m.artifactId}/${m.blockOffset}`}><button onClick={()=>onArtifact(m.artifactId,m.edge)}>Show message capture {m.artifactId}</button> · packet #{m.packetIndex} · block offset {m.blockOffset} · {m.matchBasis}</li>)}</ul></section>}
 </>}
 </section>;
}
