file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
file(WRITE "${WORK}/evidence.txt" "fixture evidence\n")
execute_process(COMMAND "${QUALIFY}" hash "${WORK}/evidence.txt" OUTPUT_VARIABLE digest OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
set(gates "")
foreach(n RANGE 1 19)
  if(n LESS 10)
    set(id "T0${n}")
  else()
    set(id "T${n}")
  endif()
  if(n GREATER 1)
    string(APPEND gates ",")
  endif()
  string(APPEND gates "{\"id\":\"${id}\",\"status\":\"passed\",\"reason\":\"verifier fixture only\",\"evidence\":[\"evidence.txt\"]}")
endforeach()
set(body "{\"apiVersion\":\"graphlab.qualification/v1\",\"runtimeLock\":\"evidence.txt\",\"sourceArchive\":\"evidence.txt\",\"workloadArchive\":\"evidence.txt\",\"capacityReport\":\"evidence.txt\",\"artifacts\":[{\"path\":\"evidence.txt\",\"sha256\":\"${digest}\"}],\"gates\":[${gates}]}")
file(WRITE "${WORK}/manifest.json" "${body}")
execute_process(COMMAND "${QUALIFY}" verify "${WORK}/manifest.json" RESULT_VARIABLE result OUTPUT_QUIET)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "valid qualification fixture rejected")
endif()
execute_process(COMMAND "${QUALIFY}" verify manifest.json WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE result OUTPUT_QUIET)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "relative manifest path rejected")
endif()
string(REPLACE "\"status\":\"passed\"" "\"status\":\"partial\"" partial "${body}")
file(WRITE "${WORK}/manifest.json" "${partial}")
execute_process(COMMAND "${QUALIFY}" verify "${WORK}/manifest.json" RESULT_VARIABLE result OUTPUT_QUIET)
if(NOT result EQUAL 1)
 message(FATAL_ERROR "partial evidence granted qualification")
endif()
file(WRITE "${WORK}/manifest.json" "${body}")
file(APPEND "${WORK}/evidence.txt" "tampered")
execute_process(COMMAND "${QUALIFY}" verify "${WORK}/manifest.json" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(NOT result EQUAL 2)
 message(FATAL_ERROR "tampered evidence accepted")
endif()
file(WRITE "${WORK}/evidence.txt" "fixture evidence\n")
string(REPLACE "\"id\":\"T19\"" "\"id\":\"T18\"" duplicate "${body}")
file(WRITE "${WORK}/manifest.json" "${duplicate}")
execute_process(COMMAND "${QUALIFY}" verify "${WORK}/manifest.json" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(NOT result EQUAL 2)
 message(FATAL_ERROR "duplicate/missing gate accepted")
endif()
get_filename_component(work_name "${WORK}" NAME)
file(WRITE "${WORK}/../${work_name}-outside.txt" "fixture evidence\n")
string(REPLACE "\"path\":\"evidence.txt\"" "\"path\":\"../${work_name}-outside.txt\"" traversal "${body}")
file(WRITE "${WORK}/manifest.json" "${traversal}")
execute_process(COMMAND "${QUALIFY}" verify "${WORK}/manifest.json" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(NOT result EQUAL 2)
 message(FATAL_ERROR "escaping evidence path accepted")
endif()

file(REMOVE "${WORK}/../${work_name}-outside.txt")
file(WRITE "${WORK}/empty" "")
execute_process(COMMAND "${QUALIFY}" hash "${WORK}/empty" OUTPUT_VARIABLE empty_hash OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT empty_hash STREQUAL "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
 message(FATAL_ERROR "SHA-256 known answer failed")
endif()
