file(MAKE_DIRECTORY "${WORK}")
function(check_summary mode expected)
 set(samples "")
 foreach(profile baseline telemetry capture)
  foreach(rate 250 1000 4000)
   foreach(repeat RANGE 0 1)
    set(rtt 100)
    set(observation "null")
    if(profile STREQUAL "capture")
     set(observation "[{\"id\":\"worker\",\"statistics\":{\"dropped\":0}}]")
     if(mode STREQUAL "drops")
      set(observation "[{\"id\":\"worker\",\"statistics\":{\"dropped\":null}}]")
     elseif(mode STREQUAL "absent" OR mode STREQUAL "isolated")
      set(observation "[]")
     elseif(mode STREQUAL "latency")
      set(rtt null)
     elseif(mode STREQUAL "gap" AND rate EQUAL 250 AND repeat EQUAL 1)
      set(observation "[]")
     endif()
    endif()
    if(mode STREQUAL "baseline" AND profile STREQUAL "baseline")
     set(rtt null)
    endif()
    if(NOT samples STREQUAL "")
     string(APPEND samples ",")
    endif()
    string(APPEND samples "{\"targetRequestsPerSecond\":${rate},\"profile\":\"${profile}\",\"hostCpuBusyPercent\":1,\"rttP95Us\":${rtt},\"receivedRequestsPerSecond\":${rate},\"lossFraction\":0,\"captureBytesPerSecond\":0,\"hostPagingReadKiBPerSecond\":0,\"hostPagingWriteKiBPerSecond\":0,\"controllerRssKiB\":100,\"withinSampleEnvelope\":true,\"captureObservation\":${observation}}")
   endforeach()
  endforeach()
 endforeach()
 set(edges 1)
 if(mode STREQUAL "isolated")
  set(edges 0)
 endif()
 file(WRITE "${WORK}/${mode}.json" "{\"apiVersion\":\"graphlab.capacity/v1\",\"edges\":${edges},\"shape\":\"fixture\",\"samples\":[${samples}]}")
 execute_process(COMMAND "${QUALIFY}" summarize "${WORK}/${mode}.json" OUTPUT_VARIABLE output COMMAND_ERROR_IS_FATAL ANY)
 if(NOT output MATCHES "${expected}")
  message(FATAL_ERROR "${mode}: missing expected summary: ${output}")
 endif()
endfunction()
check_summary(valid "no drops observed")
check_summary(drops "unknown [|] pass [|] incomplete")
check_summary(absent "unknown [|] pass [|] incomplete")
check_summary(latency "capture [|] 250.00 [|] 0.00 [|] unknown [|] 1.00 [|] 0.00 [|] unknown")
check_summary(baseline "capture [|] 250.00 [|] 0.00 [|] 100.00 [|] 1.00 [|] 0.00 [|] unknown")
check_summary(gap "1000 [|] capture [^\n]*unknown [|] pass [|] incomplete")
check_summary(isolated "no drops observed")
