file(MAKE_DIRECTORY "${WORK}")
function(check_summary mode expected)
 set(samples "")
 foreach(profile baseline telemetry capture)
  foreach(rate 250 1000 4000)
   foreach(repeat RANGE 0 1)
    set(rtt 100)
    set(observation "null")
    if(profile STREQUAL "capture")
     set(observation "[{\"id\":\"worker\",\"statistics\":{\"dropped\":0}}]")
     if(mode STREQUAL "drops")
      set(observation "[{\"id\":\"worker\",\"statistics\":{\"dropped\":null}}]")
     elseif(mode STREQUAL "absent" OR mode STREQUAL "isolated")
      set(observation "[]")
     elseif(mode STREQUAL "latency")
      set(rtt null)
     elseif(mode STREQUAL "gap" AND rate EQUAL 250 AND repeat EQUAL 1)
      set(observation "[]")
     endif()
    endif()
    if(mode STREQUAL "baseline" AND profile STREQUAL "baseline")
     set(rtt null)
    endif()
    if(NOT samples STREQUAL "")
     string(APPEND samples ",")
    endif()
    string(APPEND samples "{\"targetRequestsPerSecond\":${rate},\"profile\":\"${profile}\",\"hostCpuBusyPercent\":1,\"rttP95Us\":${rtt},\"receivedRequestsPerSecond\":${rate},\"lossFraction\":0,\"captureBytesPerSecond\":0,\"hostPagingReadKiBPerSecond\":0,\"hostPagingWriteKiBPerSecond\":0,\"controllerRssKiB\":100,\"withinSampleEnvelope\":true,\"captureObservation\":${observation}}")
   endforeach()
  endforeach()
 endforeach()
 set(edges 1)
 if(mode STREQUAL "isolated")
  set(edges 0)
 endif()
 file(WRITE "${WORK}/${mode}.json" "{\"apiVersion\":\"graphlab.capacity/v1\",\"edges\":${edges},\"shape\":\"fixture\",\"samples\":[${samples}]}")
 execute_process(COMMAND "${QUALIFY}" summarize "${WORK}/${mode}.json" OUTPUT_VARIABLE output COMMAND_ERROR_IS_FATAL ANY)
 if(NOT output MATCHES "${expected}")
  message(FATAL_ERROR "${mode}: missing expected summary: ${output}")
 endif()
endfunction()
check_summary(valid "no drops observed")
check_summary(drops "unknown [|] pass [|] incomplete")
check_summary(absent "unknown [|] pass [|] incomplete")
check_summary(latency "capture [|] 250.00 [|] 0.00 [|] unknown [|] 1.00 [|] 0.00 [|] unknown")
check_summary(baseline "capture [|] 250.00 [|] 0.00 [|] 100.00 [|] 1.00 [|] 0.00 [|] unknown")
check_summary(gap "1000 [|] capture [^\n]*unknown [|] pass [|] incomplete")
check_summary(isolated "no drops observed")
# Sustained reports use a distinct, complete six-sample matrix; short runs must
# never receive its duration claim. This is synthetic summarizer input only.
file(READ "${WORK}/valid.json" sustained)
string(JSON sustained SET "${sustained}" mode "\"sustained-m6\"")
set(selected "[]")
set(index 0)
foreach(i RANGE 0 17)
 string(JSON sample GET "${sustained}" samples ${i})
 string(JSON rate GET "${sample}" targetRequestsPerSecond)
 if(rate EQUAL 1000)
  string(JSON sample SET "${sample}" durationSeconds 300)
  string(JSON sample SET "${sample}" monitorCount 300)
  string(JSON sample SET "${sample}" controllerRssMaxKiB 150)
  string(JSON sample SET "${sample}" checks "{\"readyThroughout\":true,\"workerContinuityAndZeroSourceDrops\":true,\"deliveryLoss\":true,\"achievedRate\":true,\"rtt\":true,\"hostCpu\":true,\"availableMemory\":true,\"controllerRssGrowth\":true}")
  string(JSON selected SET "${selected}" ${index} "${sample}")
  math(EXPR index "${index}+1")
 endif()
endforeach()
string(JSON sustained SET "${sustained}" samples "${selected}")
file(WRITE "${WORK}/synthetic-sustained.json" "${sustained}")
execute_process(COMMAND "${QUALIFY}" summarize "${WORK}/synthetic-sustained.json" OUTPUT_VARIABLE output COMMAND_ERROR_IS_FATAL ANY)
if(NOT output MATCHES "two 300-second samples")
 message(FATAL_ERROR "Missing sustained scope")
endif()
if(NOT output MATCHES "[|] 150 [|]")
 message(FATAL_ERROR "Sustained peak RSS was replaced by an endpoint snapshot")
endif()
string(JSON sustained SET "${sustained}" samples 0 durationSeconds 10)
file(WRITE "${WORK}/short-sustained.json" "${sustained}")
execute_process(COMMAND "${QUALIFY}" summarize "${WORK}/short-sustained.json" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
 message(FATAL_ERROR "Short run mislabeled as sustained")
endif()
