set(prefix "${BUILD}/package-test/install")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD}" --prefix "${prefix}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE failure)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Install failed: ${failure}")
endif()
foreach(node IN ITEMS a b)
  set(consumer_build "${BUILD}/package-test/consumer-${node}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -G "${GENERATOR}" -S "${SOURCE}/tests/consumer" -B "${consumer_build}" "-DCMAKE_PREFIX_PATH=${prefix}" "-DCMAKE_CXX_COMPILER=${CXX}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE failure)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Independent consumer configure failed: ${failure}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${consumer_build}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE failure)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Independent consumer build failed: ${failure}")
  endif()
  execute_process(COMMAND "${consumer_build}/node" RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Independent consumer execution failed")
  endif()
endforeach()
