file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
file(COPY "${SOURCE}/topologies/triangle.yaml" "${SOURCE}/topologies/artifacts.lock.json" DESTINATION "${WORK}")
file(SHA256 "${WORK}/triangle.yaml" before_topology)
file(SHA256 "${WORK}/artifacts.lock.json" before_lock)
foreach(mode IN ITEMS validate plan)
  execute_process(COMMAND "${LAB}" ${mode} triangle.yaml --lock artifacts.lock.json WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE failure)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "CLI failed: ${failure}")
  endif()
endforeach()
execute_process(COMMAND "${LAB}" plan triangle.yaml --lock artifacts.lock.json WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE result OUTPUT_VARIABLE repeated)
if(NOT result EQUAL 0 OR NOT repeated STREQUAL output)
  message(FATAL_ERROR "Repeated plan changed")
endif()
file(SHA256 "${WORK}/triangle.yaml" after_topology)
file(SHA256 "${WORK}/artifacts.lock.json" after_lock)
file(GLOB files "${WORK}/*")
list(LENGTH files count)
if(NOT count EQUAL 2 OR NOT before_topology STREQUAL after_topology OR NOT before_lock STREQUAL after_lock)
  message(FATAL_ERROR "CLI mutated input directory")
endif()
execute_process(COMMAND "${LAB}" apply WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE rejected OUTPUT_QUIET ERROR_QUIET)
if(rejected EQUAL 0)
  message(FATAL_ERROR "Unsupported execution command accepted")
endif()
