import {test,expect} from '@playwright/test';
import {execFileSync,spawn} from 'node:child_process';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
test('capture inspector metadata matches Linux manifests and PCAPNG records',async({page,request})=>{
 test.skip(!process.env.GRAPHLAB_INSPECTORS_LIVE,'Requires dedicated Linux services');test.setTimeout(180000);
 const root=process.env.GRAPHLAB_LIVE_ROOT??'/var/tmp/gl6-inspectors-20260923',base='http://127.0.0.1:18098',config=`${process.env.HOME}/.lima/graphlab/ssh.config`;
 const ssh=(cmd:string)=>execFileSync('ssh',['-F',config,'lima-graphlab',cmd]);
 const tunnel=spawn('ssh',['-F',config,'-N','-L','18098:127.0.0.1:18098','lima-graphlab'],{stdio:'ignore'});let runId='',headers:any;
 try{
 await expect.poll(async()=>{try{return(await fetch(base)).status;}catch{return 0;}}).toBe(200);
 await page.goto(base);await page.getByLabel('Operator credential').fill(ssh(`cat ${root}/password`).toString().trim());await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'inspectors',exact:true})).toBeVisible();
 headers={Origin:base,'X-CSRF-Token':(await(await page.request.get(`${base}/api/v1/session`)).json()).csrf};
 for(const old of (await(await page.request.get(`${base}/api/v1/runs`)).json()).items.filter((r:any)=>r.state!=='destroyed')){const j=await(await page.request.post(`${base}/api/v1/runs/${old.id}/operations`,{headers,data:{operation:old.state==='reconciling'?'recover':'destroy',expectedRevision:old.revision,idempotencyKey:crypto.randomUUID()}})).json();await expect.poll(async()=>(await(await page.request.get(`${base}/api/v1/jobs/${j.jobId}`)).json()).state,{timeout:30000}).toBe('succeeded');}
 await page.reload();await expect(page.getByRole('heading',{name:'inspectors',exact:true})).toBeVisible();
 await page.route('**/api/v1/runs',async route=>route.request().method()==='POST'?route.continue({postData:JSON.stringify({...route.request().postDataJSON(),capturePolicy:{runBytes:67108864,reserveBytes:1048576,rotateBytes:1048576,rotateSeconds:60}})}):route.continue());
 await page.getByRole('button',{name:'Start selected topology'}).click();await expect.poll(async()=>(await(await page.request.get(`${base}/api/v1/runs`)).json()).items.filter((r:any)=>r.state==='ready').length,{timeout:60000}).toBe(1);
 runId=(await(await page.request.get(`${base}/api/v1/runs`)).json()).items.find((r:any)=>r.state!=='destroyed').id;
 await expect.poll(async()=>(await(await page.request.get(`${base}/api/v1/runs/${runId}`)).json()).health?.nodes?.length||0,{timeout:15000}).toBeGreaterThan(0);
 const detail=await(await page.request.get(`${base}/api/v1/runs/${runId}`)).json(),container=detail.health.nodes.find((n:any)=>n.id==='a').containerId,endpoint=`${base}/api/v1/runs/${runId}/process-logs`;
 const post=(suffix:string,data:any)=>page.request.post(`${endpoint}/${suffix}`,{headers,data});const query=async()=>(await post('query',{node:'a'})).json();
 ssh(`sudo docker exec ${container} /bin/sh -c 'printf "durable-marker-\\377-<script>\\n" > /proc/1/fd/1'`);
 let artifact:any;await expect.poll(async()=>{for(const item of (await query()).items){const r=await(await post('download',{node:'a',id:item.id})).json();if(Buffer.from(r.base64,'base64').includes(Buffer.from('durable-marker'))){artifact=r;return true;}}return false;},{timeout:30000}).toBe(true);
 const started=ssh(`sudo docker inspect --format '{{.State.StartedAt}}' ${container}`).toString().trim(),actual=ssh(`sudo docker logs --timestamps --tail 200 --since ${started} ${container} 2>&1`);expect(Buffer.from(artifact.base64,'base64')).toEqual(actual);expect(actual.includes(Buffer.from("durable-marker"))).toBe(true);
 expect((await request.post(`${endpoint}/query`,{headers:{Origin:base},data:{node:'a'}})).status()).toBe(401);expect((await page.request.post(`${endpoint}/query`,{headers:{Origin:base},data:{node:'a'}})).status()).toBe(403);expect((await page.request.post(`${endpoint}/query`,{headers:{...headers,Origin:'http://wrong.invalid'},data:{node:'a'}})).status()).toBe(403);expect((await post('download',{node:'b',id:artifact.id})).status()).toBe(404);
 ssh(`sudo docker exec ${container} /bin/sh -c 'i=0; while [ "$i" -lt 400 ]; do echo rollover-$i; i=$((i+1)); done > /proc/1/fd/1'`);
 await expect.poll(async()=>(await query()).items[0]?.id,{timeout:30000}).not.toBe(artifact.id);const newest=await(await post('download',{node:'a',id:(await query()).items[0].id})).json();expect(Buffer.from(newest.base64,'base64').includes(Buffer.from('durable-marker'))).toBe(false);expect(newest.omissionPossible).toBe(true);
 ssh(`sudo docker exec ${container} /bin/sh -c 'dd if=/dev/zero bs=70000 count=1 2>/dev/null | tr "\\000" x > /proc/1/fd/1; printf "\\n" > /proc/1/fd/1'`);
 let truncated:any;await expect.poll(async()=>{const q=await query();truncated=q.items.find((i:any)=>i.truncated);return Boolean(truncated);},{timeout:30000}).toBe(true);expect(truncated.size).toBe('65536');const bounded=await(await post('download',{node:'a',id:truncated.id})).json(),longRuntime=ssh(`sudo docker logs --timestamps --tail 200 --since ${started} ${container} 2>&1`);expect(Buffer.from(bounded.base64,'base64')).toEqual(longRuntime.subarray(-65536));
 await page.getByText('Accessible inventory · all nodes and data edges').click();await page.getByRole('button',{name:/^a · docker · runtime/}).click();await page.getByRole('button',{name:'Logs',exact:true}).click();await page.getByRole('button',{name:'Retained log artifacts',exact:true}).click();await page.getByRole('button',{name:`Inspect log ${artifact.id}`,exact:true}).click();await expect(page.locator('pre.console-log')).toContainText('durable-marker');expect(await page.locator('pre.console-log script').count()).toBe(0);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:`Download log ${artifact.id}`,exact:true}).click();const stream=await(await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks)).toEqual(actual);await page.getByRole('region',{name:'Retained process logs'}).screenshot({path:resolve('../../docs/validation/inspectors-live-logs.png')});
 await page.getByRole('button',{name:'Quiesce',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'stop: succeeded'})).toBeVisible({timeout:30000});const proof=JSON.parse(ssh(`sudo python3 ${process.env.GRAPHLAB_LIVE_SOURCE??'/tmp/graphlab-inspectors-20260923'}/tests/qualification/capture_metadata.py ${root}/state/captures ${runId}`).toString());
 const catalog=(await(await page.request.get(`${base}/api/v1/runs/${runId}/artifacts`)).json()).items;
 for(const expected of proof){expect(catalog.find((x:any)=>x.id===expected.id)).toMatchObject(expected);}
 const chosen=catalog.find((x:any)=>x.id===proof[0].id),captureChunks:Buffer[]=[];let offset='0';for(;;){const chunk=await(await page.request.get(`${base}/api/v1/runs/${runId}/artifacts/${chosen.id}/chunks/${offset}`)).json();captureChunks.push(Buffer.from(chunk.base64,'base64'));if(chunk.eof)break;expect(chunk.next).not.toBe(offset);offset=chunk.next;}expect(`sha256:${createHash('sha256').update(Buffer.concat(captureChunks)).digest('hex')}`).toBe(chosen.sha256);
 expect((await request.get(`${base}/api/v1/runs/${runId}/artifacts`)).status()).toBe(401);expect((await page.request.get(`${base}/api/v1/runs/missing/artifacts/${chosen.id}/chunks/0`)).status()).toBe(404);
 console.log(JSON.stringify({captureArtifacts:proof.length,packets:proof.reduce((sum:number,x:any)=>sum+Number(x.packets),0),independentPcapngAndManifestComparison:true}));
 await page.getByText(`Capture metadata ${proof[0].id}`,{exact:true}).click();await expect(page.locator(`[id="artifact-${proof[0].id}"]`)).toContainText(proof[0].captureInterface);await page.locator(`[id="artifact-${proof[0].id}"]`).screenshot({path:resolve('../../docs/validation/inspectors-live-capture.png')});
 // Restart only this stopped fixture workload: captures are finalized and the new gate starts held.
 ssh(`sudo docker restart ${container}`);
 ssh(`sudo docker exec ${container} /bin/sh -c 'printf "new-process-generation\\n" > /proc/1/fd/1'`);
 let restartedLog:any;await expect.poll(async()=>{const q=await query();restartedLog=q.items.find((i:any)=>i.generation!==artifact.generation);return Boolean(restartedLog);},{timeout:30000}).toBe(true);
 const restartedBytes=await(await post('download',{node:'a',id:restartedLog.id})).json();expect(Buffer.from(restartedBytes.base64,'base64').includes(Buffer.from('new-process-generation'))).toBe(true);
 expect((await(await post('download',{node:'a',id:artifact.id})).json()).base64).toBe(artifact.base64);
 console.log(JSON.stringify({workloadRestart:true,distinctLogGeneration:true,priorArtifactRetained:true}));
 ssh(`sudo systemctl stop ${process.env.GRAPHLAB_LIVE_AGENT??'graphlab-inspectors-agent'}`);ssh(`sudo systemd-run --unit=${process.env.GRAPHLAB_LIVE_AGENT??'graphlab-inspectors-agent'} --property=KillMode=process ${process.env.GRAPHLAB_LIVE_SOURCE??'/tmp/graphlab-inspectors-20260923'}/build/dev/lab-agent --socket ${root}/rpc/agent.sock --topologies ${root} --lock ${root}/artifacts.lock.json --state ${root}/state --allow-uid 501`);
 await expect.poll(async()=>{try{return(await post('download',{node:'a',id:artifact.id})).status();}catch{return 0;}}).toBe(202);
 const r=await(await page.request.get(`${base}/api/v1/runs/${runId}`)).json(),job=await(await page.request.post(`${base}/api/v1/runs/${runId}/operations`,{headers,data:{operation:r.state==='reconciling'?'recover':'destroy',expectedRevision:r.revision,idempotencyKey:crypto.randomUUID()}})).json();await expect.poll(async()=>(await(await page.request.get(`${base}/api/v1/jobs/${job.jobId}`)).json()).state,{timeout:30000}).toBe('succeeded');expect((await(await page.request.get(`${base}/api/v1/runs/${runId}`)).json()).state).toBe('destroyed');expect((await(await post('download',{node:'a',id:artifact.id})).json()).base64).toBe(artifact.base64);
 await page.getByLabel('Run artifacts').selectOption(runId);await page.getByRole('button',{name:'Logs',exact:true}).click();await page.getByRole('button',{name:'Retained log artifacts',exact:true}).click();await page.getByRole('button',{name:`Inspect log ${artifact.id}`,exact:true}).click();await expect(page.locator('pre.console-log')).toContainText('durable-marker');
 console.log(JSON.stringify({runId,id:artifact.id,bytes:actual.length,independentComparison:true,authorization:true,rollover:true,restart:true,retainedAfterDestruction:true}));
 }finally{if(runId){const r=await(await page.request.get(`${base}/api/v1/runs/${runId}`)).json();if(r.state!=='destroyed')await page.request.post(`${base}/api/v1/runs/${runId}/operations`,{headers,data:{operation:r.state==='reconciling'?'recover':'destroy',expectedRevision:r.revision,idempotencyKey:crypto.randomUUID()}});}tunnel.kill();}
});
